<?php
session_start();
require __DIR__ . '/../../config/index.php';
secure_auth_ch();
$Modulo = '32';
ExisteModRol($Modulo);
borrarLogs(__DIR__ . '/logs/', 10, '.log');

$ID_CLIENTE = $_SESSION['ID_CLIENTE'] ?? '';
$RECID_CLIENTE = $_SESSION['RECID_CLIENTE'] ?? '';
$APIMOBILEHRP = $_SESSION['APIMOBILEHRP'] ?? '';
$CLIENTE = $_SESSION['CLIENTE'] ?? '';

$ID_CLIENTE_MOBILE = $_SESSION['ID_CLIENTE_MOBILE'] ?? '';
$RECID_CLIENTE_MOBILE = $_SESSION['RECID_CLIENTE_MOBILE'] ?? '';
$APIMOBILEHRP_MOBILE = $_SESSION['APIMOBILEHRP_MOBILE'] ?? '';
$CLIENTE_MOBILE = $_SESSION['CLIENTE_MOBILE'] ?? '';

$_SESSION['ID_CLIENTE_MOBILE'] = $ID_CLIENTE_MOBILE ? $_SESSION['ID_CLIENTE_MOBILE'] : $ID_CLIENTE;
$_SESSION['RECID_CLIENTE_MOBILE'] = $RECID_CLIENTE_MOBILE ? $_SESSION['RECID_CLIENTE_MOBILE'] : $RECID_CLIENTE;
$_SESSION["APIMOBILEHRP_MOBILE"] = $APIMOBILEHRP_MOBILE ? $_SESSION["APIMOBILEHRP_MOBILE"] : $APIMOBILEHRP;
$_SESSION["CLIENTE_MOBILE"] = $CLIENTE_MOBILE ? $_SESSION["CLIENTE_MOBILE"] : $CLIENTE;

require pagina('mobile.php');